#!/usr/bin/env fish

if test (detect_distro) = 'macOS'
  # We assume Xcode CLI Tools and Homebrew are already installed if yadm is
  # running this.
  # If that's somehow not the case, run the following in a *Bash* shell first:
  #   xcode-select --install
  #   /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  
  # Install all bundled brews, plus GUI applications via Homebrew Cask and
  # the MAS project for Homebrew
  brew bundle --global

  # Set iTerm2 to load configuration from a custom location
  defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/.config/iterm2"
  defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

  # Install iTerm2 shell integration for fish
  curl -L https://iterm2.com/shell_integration/fish -o ~/.config/iterm2/.iterm2_shell_integration.fish
end
